bestof/urls.py
from django.conf.urls import patterns, url

from bestof import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='bestof_index')
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from mezzanine.core.views import direct_to_template


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = patterns("",

    url(r'^ebook/', include('blogebook.urls')),
    url(r'^bestof/', include('bestof.urls')),
    url("^donate/", direct_to_template, {"template": "donate.html"}, name="donate"),
    url("^subscribe/", direct_to_template, {"template": "subscribe.html"}, name="subscribe"),

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
    url(r'^content/', include('sitecontent.urls')),


    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    #url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    # url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

bestof/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()
    sort_index = models.IntegerField()

class Entry(models.Model):
    title = models.CharField(max_length=250)
    url = models.URLField()
    non_affiliate_url = models.URLField(null=True)
    description = models.TextField()
    pub_date = models.DateTimeField('date published')
    slug = models.SlugField()
    category = models.ForeignKey(Category)
    sort_index = models.IntegerField()

bestof/views.py
# Create your views here.
from bestof.utils import render

from bestof.models import Category, Entry

def index(request):
    categories = Category.objects.order_by('sort_index').all().select_related()
    return render(request, 'bestof/index.html', {'categories': categories})

bestof/templates/bestof/index.html
{% extends "base.html" %}

{% block meta_title %}
{% if page %}
{{ page.title }}
{% else %}
Best-of
{% endif %}
{% endblock %}

{% block main %}
<h1>Mes favoris</h1>
<p>Je vous propose ici les articles, livres et vidéos qui ont fait une <strong>différence pour moi</strong>. Je me dis que s'ils m'ont servis, ils pourront surement vous servir aussi. N'hésitez d'ailleurs pas à m'en proposer d'autres via la <a href="/à-propos">page contact</a>, je serais ravi de découvrir de nouvelles perles !</p>

<p><em><strong>Note de transparence</strong> :</em> si vous achetez un de ces livres sur Amazon via les liens ci-dessous, je toucherai une commission de 5%. L'intégralité des montants gagnés est utilisée pour acheter d'autres livres. Je vous donne aussi les liens « non affiliés », à vous de choisir lequel vous souhaitez utiliser.</p>


{% for category in categories %}
    {% if category.entry_set.all.count != 0 %}
    <div class="row">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><h4>{{ category.name }}</h4></div>
                <div class="panel-body">
                    <ul class="entries">
                    {% for entry in category.entry_set.all %}
                    <li><a href="{{entry.url}}"><strong>{{ entry.title }}</strong></a>{% if entry.non_affiliate_url %}, <a href="{{entry.non_affiliate_url}}"><em>lien non affilié</em></a>{% endif %} - <span>{{entry.description|safe}}</span></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% endif %}
{% endfor %}

<div style="padding-bottom: 15px;">
    <script id='fb17wor'>(function(i){var f,s=document.getElementById(i);f=document.createElement('iframe');f.src='//api.flattr.com/button/view/?uid=vjousse&button=compact&url='+encodeURIComponent(document.URL);f.title='Flattr';f.height=20;f.width=110;f.style.borderWidth=0;s.parentNode.insertBefore(f,s);})('fb17wor');</script>
</div>
{% endblock %}